server.port: 8080
server.address: 127.0.0.1

myAuth:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: myclient
      clientSecret: myclientsecret
      grant-type: authorization_code
      scope: read
    resource:
      userInfoUri: http://localhost:9999/uaa/user

facebook:
    client:
      clientId: 1189110511209604
      clientSecret: 5d3bef32631e0d5c926f46d209cad34b
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

google:
  client:
    clientId: 373151098925-khp7qhtmet5imvop7reipjpi4ipbm1th.apps.googleusercontent.com
    clientSecret: 8sH1y0FwacAAB-TArWDK9Z60
    accessTokenUri:  https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    authenticationScheme: query
    clientAuthenticationScheme: query
    scope: profile
  resource:
    userInfoUri: https://www.googleapis.com/plus/v1/people/me

vk:
          client:
            clientId: 5910725
            clientSecret: XOGfHwsOPWHKSukUHhy5
            accessTokenUri: https://oauth.vk.com/access_token
            userAuthorizationUri: https://oauth.vk.com/authorize
            tokenName: code
            authenticationScheme: query
            clientAuthenticationScheme: form
            grant-type: authorization_code
          resource:
            userInfoUri: https://api.vk.com/method/users.get